title = "Cyanide"
base_url = "https://blog.mapotofu.org"
theme = "nutshell"
taxonomies = [{ name = "categories" }]
compile_sass = true

generate_feeds = true
generate_sitemap = true
generate_robots_txt = true

[extra]

[markdown]
highlight_code = true
highlight_theme = "Tomorrow"
render_emoji = true
