name: pages

on:
  push:
    branches: [ blog ]
  pull_request:
    branches: [ blog ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: build pages
      run: |
        sudo apt install -y wget git
        wget -q -O - \
        "https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xzf - -C /usr/local/bin
        zola build
        cd public && touch .nojekyll
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'public'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
